### ISSUE TITLE
Particular license? 

### ISSUE THREAD

**Issue by sutyrin** [IS2AI/TatarTTS#1]
Hello, thanks for publishing the paper and the model — these are maginificent! 

What is the particular open source license that the model is licensed with? Is this BSD or MIT?

I'd expect to find some `LICENSE` file in this repository, please guide me. 

Thanks!

**Comment by akuzdeuov** [comment]
Hello,

Thanks for your interest in our work! The models are available under the CC-BY-4.0 license. I added ```LICENSE``` file to the repo.
